/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'IBytesize:github': typeof import('~icons/bytesize/github')['default']
    'IEp:back': typeof import('~icons/ep/back')['default']
    'IEp:eleme': typeof import('~icons/ep/eleme')['default']
    'IEp:plus': typeof import('~icons/ep/plus')['default']
    'IMaterialSymbolsLight:code': typeof import('~icons/material-symbols-light/code')['default']
    'IMdi:applicationImport': typeof import('~icons/mdi/application-import')['default']
    'IMdi:cellphoneAndroid': typeof import('~icons/mdi/cellphone-android')['default']
    'IMdi:close': typeof import('~icons/mdi/close')['default']
    'IMdi:codeJson': typeof import('~icons/mdi/code-json')['default']
    'IMdi:codeTags': typeof import('~icons/mdi/code-tags')['default']
    'IMdi:desktopMac': typeof import('~icons/mdi/desktop-mac')['default']
    'IMdi:eyeOutline': typeof import('~icons/mdi/eye-outline')['default']
    'IMdi:fileTree': typeof import('~icons/mdi/file-tree')['default']
    'IMdi:folderDownload': typeof import('~icons/mdi/folder-download')['default']
    'IMdi:playCircleOutline': typeof import('~icons/mdi/play-circle-outline')['default']
    'IMdi:powerPlugOutline': typeof import('~icons/mdi/power-plug-outline')['default']
    'IMdi:redoVariant': typeof import('~icons/mdi/redo-variant')['default']
    'IMdi:shoppingOutline': typeof import('~icons/mdi/shopping-outline')['default']
    'IMdi:undoVariant': typeof import('~icons/mdi/undo-variant')['default']
    'IRaphael:ipad': typeof import('~icons/raphael/ipad')['default']
    'ISolar:alignHorizontalCenterBold': typeof import('~icons/solar/align-horizontal-center-bold')['default']
    'ISolar:alignLeftBold': typeof import('~icons/solar/align-left-bold')['default']
    'ISolar:alignRightBold': typeof import('~icons/solar/align-right-bold')['default']
    'ISolar:arrowDownLinear': typeof import('~icons/solar/arrow-down-linear')['default']
    'ISolar:arrowToTopRightBold': typeof import('~icons/solar/arrow-to-top-right-bold')['default']
    'ISolar:arrowUpLinear': typeof import('~icons/solar/arrow-up-linear')['default']
    'ISolar:copyBoldDuotone': typeof import('~icons/solar/copy-bold-duotone')['default']
    'ISolar:copyLineDuotone': typeof import('~icons/solar/copy-line-duotone')['default']
    'ISolar:textBoldBold': typeof import('~icons/solar/text-bold-bold')['default']
    'ISolar:textItalicBold': typeof import('~icons/solar/text-italic-bold')['default']
    'ISolar:textUnderlineBold': typeof import('~icons/solar/text-underline-bold')['default']
    'ISolar:trashBinMinimalisticBold': typeof import('~icons/solar/trash-bin-minimalistic-bold')['default']
    'ISolar:trashBinMinimalisticLinear': typeof import('~icons/solar/trash-bin-minimalistic-linear')['default']
    'ISolar:trashBinTrashBoldDuotone': typeof import('~icons/solar/trash-bin-trash-bold-duotone')['default']
    'ISolar:trashBinTrashOutline': typeof import('~icons/solar/trash-bin-trash-outline')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
