/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'IBi:arrowsMove': typeof import('~icons/bi/arrows-move')['default']
    'IEp:arrowUp': typeof import('~icons/ep/arrow-up')['default']
    'IEp:plus': typeof import('~icons/ep/plus')['default']
    'IMaterialSymbols:devicesOutline': typeof import('~icons/material-symbols/devices-outline')['default']
    'IMaterialSymbolsLight:alignHorizontalCenter': typeof import('~icons/material-symbols-light/align-horizontal-center')['default']
    'IMaterialSymbolsLight:alignHorizontalLeft': typeof import('~icons/material-symbols-light/align-horizontal-left')['default']
    'IMaterialSymbolsLight:alignHorizontalRight': typeof import('~icons/material-symbols-light/align-horizontal-right')['default']
    'IMaterialSymbolsLight:code': typeof import('~icons/material-symbols-light/code')['default']
    'IMaterialSymbolsLight:formatBold': typeof import('~icons/material-symbols-light/format-bold')['default']
    'IMaterialSymbolsLight:formatItalic': typeof import('~icons/material-symbols-light/format-italic')['default']
    'IMaterialSymbolsLight:formatUnderlined': typeof import('~icons/material-symbols-light/format-underlined')['default']
    IMaterialSymbolsLightFormatBold: typeof import('~icons/material-symbols-light/format-bold')['default']
    IMaterialSymbolsLightFormatItalic: typeof import('~icons/material-symbols-light/format-italic')['default']
    'IMdi:applicationImport': typeof import('~icons/mdi/application-import')['default']
    'IMdi:borderRadius': typeof import('~icons/mdi/border-radius')['default']
    'IMdi:close': typeof import('~icons/mdi/close')['default']
    'IMdi:cursorMove': typeof import('~icons/mdi/cursor-move')['default']
    'IMdi:eyeOutline': typeof import('~icons/mdi/eye-outline')['default']
    'IMdi:magnifyExpand': typeof import('~icons/mdi/magnify-expand')['default']
    'IMdi:redoVariant': typeof import('~icons/mdi/redo-variant')['default']
    'IMdi:undoVariant': typeof import('~icons/mdi/undo-variant')['default']
    'IRadixIcons:cornerBottomLeft': typeof import('~icons/radix-icons/corner-bottom-left')['default']
    'IRadixIcons:cornerBottomRight': typeof import('~icons/radix-icons/corner-bottom-right')['default']
    'IRadixIcons:cornerTopLeft': typeof import('~icons/radix-icons/corner-top-left')['default']
    'IRadixIcons:cornerTopRight': typeof import('~icons/radix-icons/corner-top-right')['default']
    'IRadixIcons:shadowInner': typeof import('~icons/radix-icons/shadow-inner')['default']
    'ISolar:arrowDownLinear': typeof import('~icons/solar/arrow-down-linear')['default']
    'ISolar:arrowToTopRightBold': typeof import('~icons/solar/arrow-to-top-right-bold')['default']
    'ISolar:arrowUpLinear': typeof import('~icons/solar/arrow-up-linear')['default']
    'ISolar:copyLineDuotone': typeof import('~icons/solar/copy-line-duotone')['default']
    'ISolar:trashBinMinimalisticLinear': typeof import('~icons/solar/trash-bin-minimalistic-linear')['default']
    ITablerMathXy: typeof import('~icons/tabler/math-xy')['default']
    'ITdesign:chevronRight': typeof import('~icons/tdesign/chevron-right')['default']
    'ITdesign:clear': typeof import('~icons/tdesign/clear')['default']
    'ITdesign:close': typeof import('~icons/tdesign/close')['default']
    'ITdesign:download': typeof import('~icons/tdesign/download')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
